### PR TITLE
Auto disable wifi and a few more tweaks

### PR DESCRIPTION
**Pull request by zeraien**
- Automatically disconnects wifi until an "admin" card is read in by the user. Default is to keep wifi on unless configured otherwise.
- Add automatic restart setting, to lessen risk of memory leaks and crashes.
- The wifi network created will have the same name as the "hostname", in case you have multiple units nearby
- Also some minor tweaks to web interface.

### CODE REVIEW

**Comment by omersiar** [comment]
Thank you. Nice job :+1:

**Comment by zeraien** [comment]
Thank you for starting the project :)

**Comment by omersiar** [comment]
- [ ] Bug first time flashed missing deviceHostname `[ INFO ] Configuring access point... Failed!`

**Comment by zeraien** [comment]
Argh, I tested it and on my device it just used the default hostname of the
esp8266 from before, but I can put in a default.

**Comment by klasrocket** [comment]
Hi. Nice work!

Whats needed to actually turn off the rf chip and gain power savings is both

`WiFi.disconnect(true);
`and 
`WiFi.forceSleepBegin(); `

as far as I understand, according to following discussions:
https://github.com/esp8266/Arduino/issues/644
https://github.com/esp8266/Arduino/issues/460
https://www.hackster.io/rayburne/esp8266-turn-off-wifi-reduce-current-big-time-1df8ae

But not sure it's easy to bring it back up again, so I simply just used a button physically connected to reset.

Would be nice to avoid wlan shutting down if its used though, will look into that.

**Comment by zeraien** [comment]
The problem is that as it stands, the forceSleepBegin can not be reversed without powercycling the device, which is a problem if you do not wish to, or can not powercycle it at will. But as I understand it, it is a feature that should work so hopefully it will be fixed in future versions of the esp8266 code.

**Comment by omersiar** [comment]
I always wanted the rfid hardware to be interrupt driven. All this bit banging beyond me, maybe rfid hardware can trigger reset, but we need atmel like wake up function.

**Pull request merged**
