### PR TITLE
Wiegand Keypad support

### PR DESCRIPTION
**Pull request by frenchie71**
Keypad support for Wiegand readers as discussed in issue #132

### CODE REVIEW

**Comment by omersiar** [comment]
Nicely done.

**Comment by omersiar** [comment]
Consider collecting the bounty, it's not much but still can get you a few ESPs :)

https://www.bountysource.com/issues/61614375-wiegand-keypad-support

**Comment by omersiar** [comment]
Also you can collect additional 15 USD if you have PayPal. Just mail me your PayPal address.

**Comment by frenchie71** [comment]
No way, please keep the moneys ;-) I had to do it anyway and the cutting edge was done in  issue #132 by koffienl anyhow - so there is not much of a merit on my side. I am glad to contribute to this great project.

**Comment by henfri** [comment]
Hello,

I see, that this has made its way into the dev branch. Thanks @frenchie71  for the work on this.
Is there any release of esprfid that includes the keypad support already?

Would [this ](https://de.aliexpress.com/item/33056522572.html?spm=a2g0o.productlist.0.0.5b4c606eV2rGHo&algo_pvid=b098170a-89be-45c7-8e58-0d503f9b0429&algo_expid=b098170a-89be-45c7-8e58-0d503f9b0429-6&btsid=77871500-9432-44d2-aebf-c2f566d1ce39&ws_ab_test=searchweb0_0,searchweb201602_10,searchweb201603_53)reader work with it?

Regards,
Hendrik

**Pull request merged**
