### PR TITLE
The returned AP mode

### PR DESCRIPTION
**Pull request by vvvyky**
The returned AP mode parameter submission is not recognized

The returned AP mode parameter submission is not recognized

### CODE REVIEW

**Comment by vvvyky** [comment]
The original submission is "fallbackmode": "1" is "fallbackmode" correctly: 1

**Comment by matjack1** [comment]
Can you please move the changes of #571 in this PR?

Also, you are moving the file to a new location, that should not happen, please amend that as well.

Then I'll test it, thank you for this.

**Comment by vvvyky** [comment]
Save as this

  if (parseInt(document.querySelector("input[name=\"fallbackmode\"]:checked").value) === 0) {
        config.network.fallbackmode = 0;
    } else {
        config.network.fallbackmode = 1;
    }
Display unchanged
    document.forms.fallbackmodeForm.fallbackmode.value = config.network.fallbackmode;

Test OK

If it is changed to document. getElementById ("fallbackmode"). value=config. network. fallbackmode; Prompt error not displayed

**Comment by matjack1** [comment]
Thank you for the bug report @vvvyky 

The bug was there, but the problem wasn't in the code that you have shared, it was with a missing rebuild of the JS files after the latest PRs merging.

I've rebuilt the assets and pushed in dev and the problem is fixed to me.

Can you please try again and open a new issue if it's not the case?

Thank you!

**Pull request closed without merging**
