### PR TITLE
Added RDM6300 support, added favicon.ico, fixed listSCAN(), ...

### PR DESCRIPTION
**Pull request by Pako2**

### CODE REVIEW

**Review by omersiar — APPROVED** [review]

**Comment by omersiar** [comment]
@Pako2 This is great, thanks.

You have worked on stable branch, actually i already made some changes to dev branch (the development branch). @arduino12 was already pushed RDM6300 support.

I will try to merge those changes together.  Nicely done.

**Comment by omersiar** [comment]
Also i try to keep firmware sizes below OTA update limits which is under 512 KB, .woff font is supported by almost every browser.

**Comment by omersiar** [comment]
Merged to dev branch 383e9fed @Pako2 Thanks again

**Comment by Pako2** [comment]
I'm glad I could contribute to your unique project.
I see that you chose the RDM6300 solution from [@arduino12](https://github.com/arduino12).
Why did you decide so?
Here are the benefits of my solution:
1) This allows simultaneous connection of two sensors (for 125kHz and 13MHz tags)
2) My "rfid125kHz.h" library supports not only the RDM6300 reader but also the [RF125-PS](https://www.aliexpress.com/store/product/RFID-125KHz-EM4100-ID-Reader-Access-Control-System-Reading-Card-Reader-Module-TTL-Low-Frequency-UART/1829717_32679324703.html) reader (it has a slightly different protocol)

And here is (perhaps the only) disadvantage:
1) Because UART hardware is used in this case, it is not possible to use boards such as NodeMcu or WeMos D1 mini (with USB / serial port converter).

However, I'm still convinced that a bare module (like ESP12) is more suitable for your great esp-rfid project. Plus, why use the "SoftwareSerial" port when a (completely unused) hardware port is available?

**Comment by omersiar** [comment]
@Pako2 Sorry i did not realize these benefits i was tired yesterday,  changes were conflicted, i even do not know if i could correctly solved them. My WeMos D1 board is dead right now, i can not test the changes with real hardware, i am limited only to emulator.

I think I need to design a better approach for multiple readers, for example readers that have SPI can be used simultaneously also can be combined with UART reader (like your approach).  Also the 512kb limit is a concern for me.  I liked the idea of your combined readers, I just did not understand the code behind it.

RF125-PS seems perfect solution for a complete board (cheap and small). I will inform @nardev if he can actually embed it to official board.

If you can prepare a new Pull Request i would be happily merge it to dev branch.

My workflow is something like that:

Make new changes, bug fixes on dev branch > test them > if it is stable enough, tag as a new version > merge them to stable branch > make a release 

stable branch never gets direct commits but only merge commits.

**Comment by nardev** [comment]
@omersiar i can and i will.

**Comment by nardev** [comment]
p.s. the JS code can me at least 50% smaller, the selectors that we use can be optimized. So that is one possible way to save some space.

**Pull request closed without merging**
