### PR TITLE
WiFi LED is now an optional feature

### PR DESCRIPTION
**Pull request by Pako2**
The subject says everything.

### CODE REVIEW

**Comment by omersiar** [comment]
@Pako2 Thank you

**Comment by omersiar** [comment]
I will correct Codacy issues later together.

**Comment by omersiar** [comment]
@Pako2 I guess i found the problem with the configuration is not being saved problem

These two lines 

https://github.com/Pako2/esp-rfid/blob/0ea0e2e52da1ceeec33f89a96ea2bf447fbc7706/src/main.cpp#L205

https://github.com/Pako2/esp-rfid/blob/0ea0e2e52da1ceeec33f89a96ea2bf447fbc7706/src/main.cpp#L221

Causing the loadConfiguration() function to be called again and again.

Can you please confirm?

**Comment by omersiar** [comment]
I simply tried to debug with below code 

```cpp
	configMode = loadConfiguration();
	if (!configMode)
	{
		fallbacktoAPMode();
		configMode = false;
	}
	else {
		configMode = true;
	}
```

**Comment by Pako2** [comment]
So far I have not understood.
Did you manage to reproduce the problem?
I do not. But perhaps it might be some setting that prevents ...
```
	configMode = loadConfiguration();
	if (!configMode)
	{
		fallbacktoAPMode();
		configMode = false;
	}
	else {
		configMode = true;
	}
```
Does your debug code help?
If so, I do not get it.
configMode is a variable and it is declared as a boolean.
The only place where the value is changed is: `configMode = loadConfiguration();` and this is within `setup()`.
I do not see that it's called repeatedly. That would have to be something like that
`configMode = loadConfiguration`, ie without parentheses, but configMode is only boolean variable, not function.

I do not see that the "fallbacktoAPMode ()" function somehow affected the configMode value.
So assigning `configMode = false` or `configMode = true` seems to me totally redundant.

But I can not rule out that you are right. I just can not understand it yet ...

**Comment by omersiar** [comment]
I really do not know, i can not test it with a hardware but maybe i can try just with plain c++ code.

I just assume (from my previous experience) if a boolean set to a function and used it, it executes assigned function to get it is status.

**Comment by omersiar** [comment]
Ok I am wrong, sorry to bother you i just tested below code

```c++
#include <iostream>

int i = 1;
bool test;

bool retBool()
{
    i++;
    if (i % 2 == 0)
    {
        return true;
    }
    else
    {
        return false;
    }
}

int main()
{
  test = retBool();
  std::cout << "First : " << test;
  std::cout << "Second : " << test;
}
```

**Pull request merged**
