### PR TITLE
Fix Home Assistant integration

### PR DESCRIPTION
**Pull request by matjack1**
This PR takes on board the fixes made in #549 plus some more.

I still need to do some testing, but if someone would like to give this a go it would be very helpful :)

Thank you @Aleks130699 for your fixes!, very helpful!

### CODE REVIEW

**Comment by Aleks130699** [comment]
@matjack1  thanks for the work, I looked at the code and saw some bad moments, firstly, Home Assistant Discovery should have the retain flag, secondly, it was not the best idea to publish statuses in the homoassistant/io topic, because the homeassistant topic is intended for configuration files, not for status files, and with this approach, several esp-rfid will publish your statuses in one place and flash to each other

**Comment by matjack1** [comment]
Thank you @Aleks130699 for reviewing!

Can you please help me to understand better where should I set the retain flag and what it does?

And for the statuses instead, what do you recommend? Which topic should I use?

**Comment by Aleks130699** [comment]
`mqttClient.publish(stopic.c_str(), 0, true, mqttBuffer.c_str());` Here in this command, the 3rd parameter is responsible for the save flag, it is needed so that, after each reboot, Home Assistant requests configuration from the MQTT broker, and it issues all messages with the retain flag, and since it is not set when sending, then this message is well  will arrive, and you will need to reload the esp-rfid in order for the device to appear again

**Comment by Aleks130699** [comment]
I would leave the topic for the message "device-name"/io or "device-name"/homeassistant, why is that ?, for Home Assistant there is no difference where to get messages, but it's easier for us to see all messages in one root topic, by device name  , and thus any number of devices will be in separate root topics like esprfid, esprfid2, esprfid3, or others, and thus the devices will not interfere with each other

**Comment by matjack1** [comment]
> `mqttClient.publish(stopic.c_str(), 0, true, mqttBuffer.c_str());` Here in this command, the 3rd parameter is responsible for the save flag, it is needed so that, after each reboot, Home Assistant requests configuration from the MQTT broker, and it issues all messages with the retain flag, and since it is not set when sending, then this message is well will arrive, and you will need to reload the esp-rfid in order for the device to appear again

Oh I see! Nice, I didn't know about that option. But in this specific case actually I think it's better without. If you restart HA it retains the esp, even if it's off. So it's not necessary in your use case. But on the flip side, with the retain flag you cannot remove an esp-rfid, as the broker sends the message every time, even if the esp is not there anymore, which is a problem that I had before.

I didn't notice the flag when porting the changes in my PR, but I actually think it's better without.

**Comment by Aleks130699** [comment]
@matjack1 just the opposite, after rebooting HA, esp-rfid will disappear from it until you reload esp-rfid,and there is a special button for deletion in HA that will delete these messages from the broker, or through the same MQTT Explorer, you can delete messages  and they will not be restored after deletion, it is better to listen to the HA user before drawing your own conclusions about how it works there

**Comment by Aleks130699** [comment]
and you should use "void mqttPublishEventHA", only for detection messages, because I repeat, these messages should be with the "RETAIN" flag, and be in the root topic "homeassistant", which should contain only device configuration files

**Comment by matjack1** [comment]
> just the opposite, after rebooting HA, esp-rfid will disappear from it until you reload esp-rfid

OK, it doesn't happen here to me, but that's fine, let's try as you say, thanks

**Comment by matjack1** [comment]
> I would leave the topic for the message "device-name"/io or "device-name"/homeassistant, why is that ?, for Home Assistant there is no difference where to get messages, but it's easier for us to see all messages in one root topic, by device name , and thus any number of devices will be in separate root topics like esprfid, esprfid2, esprfid3, or others, and thus the devices will not interfere with each other

@Aleks130699 I see, yes, you are right, I'm going to change that, thanks.

**Comment by matjack1** [comment]
OK @Aleks130699 I think I've fixed it, it works well here, better than before, thank you very much!

Can you please give it a go?

**Comment by Aleks130699** [comment]
@matjack1 Thanks now it looks good, I will test it soon

**Pull request merged**
