### PR TITLE
GPIO16 as open/close button

### PR DESCRIPTION
**Pull request by donatmarko**
This PR adds the possibility to use GPIO16 (D0) as an open/close button.

As the ESP chip contains an internal pull-down (unlike the other GPIOs) resistor on GPIO16, the button must be connected between 3V3 and GPIO16.

### CODE REVIEW

**Review by omersiar — APPROVED** [review]
Again nicely done, thank you.

**Comment by Pako2** [comment]
I would personally prefer the connection as with the other GPIO, but (of course) with an external pull-up resistor. It feels dangerous to me, connecting the supply voltage directly to some long wire line. This may cause interference and unexpected behavior.
Besides, I think there is something missing. The button that will be connected in this way will behave in reverse against others (GPIO16: idle state is LOW, other: idle state is HIGH). Perhaps I am wrong and it is somehow taken into account in the library used. I did not examine it.

**Comment by donatmarko** [comment]
The relay activation function is bound to the "falling" event of the GPIO input, so the only difference is the function runs on releasing the button with GPIO16 and on pressing it with the others.

For the resistors, I have an ESP8266 with such a button (using the internal pull-down) connected together with an approx. 5 m of wire. It works properly (yet 😃). But of course, we might add a checkbox to enable/disable the internal pull-ups/pull-down to allow using external ones.

edit: typo

**Comment by Pako2** [comment]
I have nothing against a pull-up resistor (it does not matter whether internal or external). I'm  bothered with connection with a pull-down resistor (it also does not matter whether internal or external), because in this case, the supply voltage (3.3V) is directly connected to the long wire. This is definitely more sensitive to interference than GND.

**Comment by omersiar** [comment]
I did not encounter any interference with the Arduino Uno with similar setup, i must tell i am not an expert on electronics. What is the best option to connect a button to a microcontroller?

@donatmarko did you test this? ~~Or is this on theory?~~ I think i have a matured code for this in my Uno project.

**Comment by Pako2** [comment]
I've been looking for some articles to explain this issue in detail, but I did not find anything complex.
However, some rules are repeated in more articles. In particular, the rule that the longer the wire is, the smaller the pull-up (pull-down) resistor should be (this in practice means using an external rather than an internal resistor). The longer the wire is, the more it should be to protect the input (eg. clipping schottky diodes) and use the twisted pair.
Regarding whether it is better to use pull-up or pull-down circuit, I have only found the following two references:
[As already suggested, a simple pull-down resistor should be used in all cases, or preferably a pull-up resistor, with the switch pulling the input low instead of high - that's the more normal way of doing it (there are various advantages in doing it that way).](https://www.electro-tech-online.com/threads/noisy-long-wire-effect-my-microcontroller-digital-input.92541/post-734142)  

[Use the pull up method rather than the pull down. This is because the decoupling and spike suppression is more effective.](http://forum.arduino.cc/index.php?topic=125315.msg943009#msg943009)  

But, no matter what the previous one, what is it about?
I think it's only a question of whether it's better:
A) In the case of GPIO16, use a pull-down resistor to save one external pull-up resistor (this is the ONLY benefit of this solution)
or
B) For GPIO16 use circuit with an external pull-up resistor. The advantage is, in particular, "normal" behavior, ie the reaction when pressing a button and not when it is released.

**Comment by omersiar** [comment]
~~I think with enabling PULL DOWN resistor, we do no harm for other cases, one can always choose which circuit to use with given GPIO. I may add precautions on README with the usage of this feature (or PIN).~~

I am really confused now. 

Official hardware won't be affected since it uses different circuitry.

We may let the user choose which option to use, falling or raising.

**Comment by Pako2** [comment]
I personally do not really care about that, because I'm still using GPIO16 otherwise (SPI SS).
@donatmarko:   **What reasons do you have exactly that you are choosing such a solution?**
Does this seem to be better (easier, more understandable) for other users?
In both cases (when choosing GPIO16 for this purpose), the user must be alerted to an anomaly (relative to the other GPIOs):
A) In the case of GPIO16, connect the button differently than the other GPIOs (and this will behave differently: the reaction only when the button is released as opposed to the moment of pressing)
B) In the case of GPIO16, use an external pull-up resistor (eg. 4.7 kΩ).
Because of the other benefits, I still see better variant B).
This is my last comment on this matter. I think the @omersiar should have a decisive say.

**Comment by omersiar** [comment]
Ok i discussed this with my colleague Ayberk @akarakn Electronic Engineer

He said that PULL-UP method is more appropriate in this case. I always wanted to omit busy GPIOs from the drop-down selection menu but could not implement it. Maybe with smart coding GPIO-16 can be used as SS pin or Button Pin regardless from GPIO setting.

Thanks both of you.

**Comment by nardev** [comment]
The hardware functionality already exists in ESP-RFID Realy board.

Glad to see that somebody did this. Although actually simple wiring is just fine too. But this way you can track when somebody uses this functionality.

**Comment by Blarppa** [comment]
Is it possibile to clarify how to Wire the exit button?  I had the button between 3v3 and the chosen gpio, not working...     didnt find any info?

**Comment by donatmarko** [comment]
> Is it possibile to clarify how to Wire the exit button? I had the button between 3v3 and the chosen gpio, not working... didnt find any info?

If you have chosen to use any of the GPIOs with internal pull-up resistor (all of them except GPIO16), you have to wire the pushbutton between the GPIO and GND.

**Pull request closed without merging**
