### PR TITLE
fix available flash size for 2M

### PR DESCRIPTION
**Pull request by Pako2**
+ fix available flash size for 2M (otherwise it still shows 100%)
+ adding a license agreement (MIT) to the rfid125kHz library (+ refactoring)
+ adding **Serial.begin(9600)** for RDM6300 support

### CODE REVIEW

**Review by omersiar — APPROVED** [review]
@Pako2 did you had any issue with the v0.9.0?

**Comment by omersiar** [comment]
Thanks for the fixes by the way

**Comment by Pako2** [comment]
> @Pako2 did you had any issue with the v0.9.0?

No, I have no issues.
But I have only tested RDM6300 for now, nothing else.

**Comment by omersiar** [comment]
Did you see 

https://github.com/esprfid/esp-rfid/issues/192 

I do not know what is failing.

**Pull request merged**
