### PR TITLE
Reintegration of the RDM6300 (and RF125-PS) solution

### PR DESCRIPTION
**Pull request by Pako2**
Here it is again.
Perhaps it would be appropriate to change the relevant passage in README.md.
If someone uses NodeMcu or WeMos D1 mini, then he will have a problem with the RDM6300 (or RF125-PS) connection.

### CODE REVIEW

**Comment by omersiar** [comment]
Thanks again @Pako2 .

**Comment by omersiar** [comment]
Did you have any issue of not connecting to Wireless Access Point?

**Comment by Pako2** [comment]
> Did you have any issue of not connecting to Wireless Access Point?

No. Has any problem occurred?

**Comment by omersiar** [comment]
Please see https://github.com/esprfid/esp-rfid/issues/157#issuecomment-437390635

**Comment by Pako2** [comment]
I understand, but I did not try MQTT connection.

**Comment by omersiar** [comment]
After yesterday's merge, people reporting they are not able to connect to Wi-Fi anymore (it defaults back to AP mode).  I think i need to clean my build environment, since you do not have the issue. Thanks again.

**Comment by snizzleorg** [comment]
Is there any documentation on how to connect this particular reader? I have an ESP8266 set up with this reader running my own sw but this project seems so much more versatile...

**Comment by omersiar** [comment]
It's wiegand based reader, and it is easy to connect, official board fully support wiegand based readers and dedicated pin headers.

https://github.com/esprfid/esp-rfid#pin-layout

For Wiegand based readers, you can configure D0 and D1 pins via settings page. By default, D0 is GPIO-4 and D1 is GPIO-5

**Comment by snizzleorg** [comment]
The RDM6300 is Wiegand? It only has TX connected in my case. Basically a serial port. Its also using 5V.

**Comment by Pako2** [comment]
>After yesterday's merge, people reporting they are not able to connect to Wi-Fi anymore (it defaults back to AP mode). I think i need to clean my build environment, since you do not have the issue. Thanks again.

I would like to help. I will try to install the Mosquitto server tomorrow in Windows.

**Comment by Pako2** [comment]
> The RDM6300 is Wiegand? It only has TX connected in my case. Basically a serial port. Its also using 5V.

There are versions RDM 6300 with Wiegand, but in this case we are talking about a serial port version. Connection is easy. The RDM6300 TX pin connects to the ESP8266 RX pin (hardware UART).

**Comment by snizzleorg** [comment]
I checked a little more the RDM630 is the Wiegand Variant, the RDM6300 is serial. But I guess it will still be easy. Question however is if I can use my board. In my case the TX is not connected to the hardware UART. I'm using software serial on a different PIN. (can't remember which at the moment however.

**Comment by Pako2** [comment]
I installed a MQTT broker and I'm trying it out. So far, it works well, I have no WiFi problems.

**Pull request merged**
