### PR TITLE
Fix for NTP blocking loop if connection is blocked

### LINKED ISSUE #615: NTP unnecessarily blocking loop if connection is not present
Hi! I've tried this solution on October 28 and I was so enthusiast since it worked perfectly. This new v2.0.0.rc0 doesn't work properly... can you please send me the generic.bin file before v2.0.0.rc0?
Here are some of the problems I've discovered:
- Not working in AP mode
- Page loading amount of time is very long and sometimes pages such as settings or users doesn't load at all
- User page doesn't load properly
- Cannot use PIN only mode with my wiegand reader (it read one pressed key at a time)
- Problems persists if I connect it to a Wi-Fi network in client mode

### PR DESCRIPTION
**Pull request by croggero**
Fixes #615 
NTP was blocking the loop causing 10seconds delays when executing when no NTP server could be reached. This fix will check every 10seconds and fall back to the device clock, updating it from the last NTP sync.

### CODE REVIEW

**Comment by matjack1** [comment]
Thank you very much! This is very important mistake that I did. Thank you for fixing it :)

**Comment by MaximeSharp** [comment]
Just compiled the debug firmware, it's now kind of working.

Here a few issues I've encountered : 

- scanning a admin card does trigger the wifi enable loop and the relay output will stay triggered until the wifi failed (~15 seconds)

- when starting the ESP-RFID board without any wifi available, it won't sync with the NTP server (obviously) but even if the wifi get available after, it doesn't sync with the NTP server ([DEBUG] NTP sync failed) and time will be stuck at the 1st January 1970

**Comment by matjack1** [comment]
Thanks! I'll check these

**Comment by matjack1** [comment]
hey @MaximeSharp I've just committed on `dev` a little fix for the NTP after wifi reconnect, can you please confirm that it's working?

Instead for the other one, can you please open a separate issue as I'm not sure it's related to this PR.

Thanks!

**Comment by MaximeSharp** [comment]
> hey @MaximeSharp I've just committed on `dev` a little fix for the NTP after wifi reconnect, can you please confirm that it's working?
> 
> Instead for the other one, can you please open a separate issue as I'm not sure it's related to this PR.
> 
> Thanks!

Compiled and tested, NTP sync after wifi reconnect is now working !

No problem, I will open a separate issue for the other one and add more info/logs.

**Pull request merged**
