### PR TITLE
Logfile fixes part 1

### PR DESCRIPTION
**Pull request by frenchie71**
Fixing the Watchdog Timeout due to sequential re-read of the file by using seek() and remembering the last position in the file. Takes roughly 80 ms per page.

### CODE REVIEW

**Review by omersiar — APPROVED** [review]
Huh, I was thinking I invented the wheel by that time with this page by page algo. You did a great job here, all these stuff was alien to me, now I can tell seek function actually what I wanted. Nicely done.

**Comment by frenchie71** [comment]
Well, seeking in text files is not that obvious neither - I would have done it in some similar way like you to start - problem is it doesn't scale well. But again who could know esp-rfid would take off like it did? Usually seeking is done in fixed-length-block type files. But as the requests come in sequentially from the js file we can indeed save the last position.
On this note: I am planning a handful of more enhancements to logging, but I am not too keen on doing the website gulp stuff - I am thinking about adding log maintenance download, split, truncate roll over etc. - if I changed the html and js files would you mind doing the gulp conversion stuff?

**Comment by frenchie71** [comment]
PS - for the record - this partially addresses issues #247 and #285

**Comment by omersiar** [comment]
I should check latest development on ESPAsyncWebServer library. There maybe additional fixes.

**Pull request merged**
