### PR TITLE
Fix web sockets instability

### PR DESCRIPTION
**Pull request by matjack1**
This PR attempts a fix at a long standing issue about reboots when using the web UI.

The issues that probably will be fixed by this are:

- https://github.com/esprfid/esp-rfid/issues/442
- https://github.com/esprfid/esp-rfid/issues/311
- https://github.com/esprfid/esp-rfid/issues/486
- https://github.com/esprfid/esp-rfid/issues/557

A bit of back story here: https://github.com/esprfid/esp-rfid/discussions/572

Mainly this PR is moving the processing of web sockets out of the callback to the main loop, similar to what happened recently to the MQTT messages.

Then instead of sending all the messages to all the clients, now each client receives back the messages that have requested, so potentially multiple users can access esp-rfid simultaneously.

If anyone can test this and give me a feedback would be greatly appreciated.

### CODE REVIEW

**Comment by timknowlden** [comment]
Hi @matjack1 , I would like to try this as my unit is still on the test bench, I am not sure how I can download this release to test though as still new to GitHub. I also have an issue on the version I am using where GPI05 is triggered on boot up (which triggers relay)

**Comment by matjack1** [comment]
hey @timknowlden thank you!

You can check the automated builds from here: https://github.com/esprfid/esp-rfid/actions

In particular, the latest build for this PR is here: https://github.com/esprfid/esp-rfid/actions/runs/3980992874 at the bottom of the page you can download the binaries. Let me know if you need more info. Thank you very much!

**Comment by timknowlden** [comment]
Thanks for the reply, I will try the latest very shortly.

 Im also trying to understand how GitHub works, there are Tools build for Mac, Windows and Linux, these are all ones that have to be manually compiled and platform IO is automated?

**Comment by timknowlden** [comment]
@matjack1 I have installed this build, the issue with triggering the relay persists.
My relay board is this one here:
https://templates.blakadder.com/ESP12F_Relay_X1.html

I am using GPI05, which is listed as ok to use on here: https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

So it seems as though somewhere in the code it is being triggered on start up? (my hardware settings are set to Momentary and is triggered for the same length as the 'Activate Time', it doesn't trigger on start up if set to Continuous)

I am also not having any joy with home assistant auto discovery, if I set topic to home 'assistant/rfid' or just 'rfid' as per the MQTT readme it is not picked up in home assistant automatically. 

I can communicate with it manually. It is also taking 3 or more times to save the changes as after each restart it is back to how it started.

Because my intention is to use this with a garage door opener I cannot have this trigger the door in the event of a power cut, or device reboot.

Any help appreciated.

**Comment by matjack1** [comment]
This PR is not related to your issue, I'd say, but let me try giving you a couple inputs:

- the relays are triggered at startup in the closed state. If yours is triggered in the wrong way, try to change the relay setting here: 
Schermata 2023-01-22 alle 21 50 50

- the HA autodiscovery topic is fixed, so it shouldn't be affected by your settings

Maybe let's carry on in your discussion here: https://github.com/esprfid/esp-rfid/discussions/576 if it's not related to this PR

**Comment by windy54** [comment]
Just downloaded the binary and installed the debug build.
150 users restored on first attempt.

Brilliant, promise not to find anymore issues...
Steve

**Comment by matjack1** [comment]
Thank you!

**Comment by timknowlden** [comment]
Good morning,

I have been having issues with the door opening on its own, it is registering the action as the internal button being pressed. See log,

image

**Comment by matjack1** [comment]
@timknowlden is this caused by this pull request? It seems unrelated to me. If it is unrelated, please open a separate issue and possibly provide an export of your settings and the version you are trying, so that I can better reproduce the error. Thanks!

**Comment by timknowlden** [comment]
> @timknowlden is this caused by this pull request? It seems unrelated to me. If it is unrelated, please open a separate issue and possibly provide an export of your settings and the version you are trying, so that I can better reproduce the error. Thanks!

Sorry, this is the incorrect place. I will do this later as I am away from home and my wife has switched the device off because of the opening/closing whilst nobody is home

**Comment by matjack1** [comment]
This is not perfect, it's a little improvement for stability. It works most of the time, with not too big data set. But this is the best I can pull off here :(

For doing stuff when the web UI breaks, I recommend using MQTT that is far more stable.

**Pull request merged**
