### PR TITLE
Update and clean Gulp frontend generation

### PR DESCRIPTION
**Pull request by matjack1**
I was having trouble to generate the frontend on Windows, so  I've updated the Gulp script, deleted unnecessary files and updated the documentation.

It looks straightforward now, just `npm i` and `npm start` to generate the updated files, I hope it makes sense and that the deleted files are not used for anything else.

### CODE REVIEW

**Comment by matjack1** [comment]
@omersiar can you please review this as well? I've got another PR lined up that depends on this :P

**Comment by omersiar** [comment]
It looks good to me. I remember adding builder.exe because of the emulator.  I'm confused now. :)

**Comment by matjack1** [comment]
what emulator @omersiar ? If you want I can put that file back, I just didn't find any documentation around and I think you can manage the frontend without

**Comment by omersiar** [comment]
Originally I wanted to enable people to edit web files without all development dependencies and builder.exe was born, just edit htmls and that's all. :blush:

**Comment by matjack1** [comment]
Nice @omersiar makes sense, how did you generate the builder.exe ? It didn't work for me, so that's why I removed it, I thought it was obsolete.

Instead regarding the emulator that you mentioned before, what was that?

**Comment by omersiar** [comment]
[pkg](https://github.com/vercel/pkg) can compile code to a single binary.

**Pull request merged**
