### PR TITLE
esp-rfid v2

### PR DESCRIPTION
**Pull request by matjack1**
I think it's time to release a V2 for esp-rfid :)

We need a V2 as there are a few breaking changes on the MQTT interface, but I think it's much better now.

Apart from that, the update from V1 should just work, the old configuration will work on the V2 and the new stuff should default to settings that should keep the old configuration working. If anyone has problems upgrading let me know!

I have updated all the documentation and apart from a merge with stable and a changelog update we should be ready!!

@omersiar let me know what you think :)

### CODE REVIEW

**Comment by matjack1** [comment]
I've also create a release to help trying it out, here: https://github.com/esprfid/esp-rfid/releases/tag/2.0.0.rc0

**Comment by omersiar** [comment]
This is huge 🥳 and puts a great milestone to the project thanks to all efforts you put into this,  much appreciated.

**Comment by matjack1** [comment]
Thank you @omersiar!

Meanwhile I've deployed it on our system at the local Fablab and found a little bug about the old config compatibility :)

If you can approve again would be nice :)

I'll leave the PR open for a couple weeks just in case I find anything else or if anyone testing finds any issue. Thank you Omer!!

**Review by omersiar — APPROVED** [review]
LGTM, thanks

**Comment by matjack1** [comment]
Today is the day of v2!

**Pull request merged**
