### PR TITLE
Adding the ability to reboot via the MQTT command

### PR DESCRIPTION
**Pull request by Aleks130699**

### CODE REVIEW

**Comment by Aleks130699** [comment]
#530

**Comment by matjack1** [comment]
Thank you @Aleks130699 for this! Could you please also add the documentation in the `README-MQTT.md` file?

**Comment by Aleks130699** [comment]
Перезагрузка использует ту же структуру сообщения, что и другие команды.
`{
    "cmd":"reboot",
    "doorip":"(The ESP-RFID IP of the door to open as String)"
}`

**Comment by matjack1** [comment]
@Aleks130699 I mean that part of this PR you should also update the `README-MQTT.md` file, so that future people will know what you can do with MQTT

**Comment by Aleks130699** [comment]
I have some more improvements on mqtt, including improvements on integration with Home Assistant, is it better to use a separate PR? or publish to this one?

**Comment by matjack1** [comment]
Please use a new one @Aleks130699 as it's easier to manage and give feedback.

I'm also working on fixing the Homeassistant integration, if you want to wait a couple days I should be able to finish that.

**Comment by matjack1** [comment]
On this PR instead @Aleks130699 the documentation is added in between the description of another paragraph.

But before that, why are we adding this? What's the point of restarting the esp-rfid when it's connected to the wifi and mqtt and able to respond? If there's a problem we should fix that, right?

**Comment by Aleks130699** [comment]
@matjack1 This functionality was developed more by the will of one of the users, and is not a high priority #530

**Comment by matjack1** [comment]
I'm going to close this in favour of: https://github.com/esprfid/esp-rfid/pull/552 which I think is more useful as you can reboot also if the system is not connected via MQTT.

If you have more info/use cases we can reopen though!

**Pull request closed without merging**
