### PR TITLE
marelab V1.1 pull branch for ESP-RFID 1.02

### PR DESCRIPTION
**Pull request by marelab**
Adds to GUI and mqtt.esp for adding these MQTT functions:

* Reading all user data over MQTT
* Sending User data to RFID-DOOR/ESP-RFID over MQTT
* Sending door open command over MQTT
* Sending Sync of a RFID-DOOR (IP/Hostname) over MQTT
* Configure Sync interval over ESP-RFID GUI
* Deleting all User of a ESP-RFID device over MQTT
* Logging event & access over MQTT and disable the local file logging

Description in the README-ADDON.md

NODE-RED flow & GUI to centralize managment of ESP-RFID devices & users can be found 
here https://github.com/marelab/rfid-door-node-red

### CODE REVIEW

**Comment by omersiar** [comment]
Thank you, currently these are most wanted features by community, much appreciated. 

Also we need to merge these onto dev branch, the development goes on dev branch then we make a release with all commits, usually I make pre-release for community to test then when we convinced we make actual release.

edit: grammar

**Comment by marelab** [comment]
I will prepare a pull foor the dev branch but might takes a bit time.

**Comment by omersiar** [comment]
No need to rush, you can check CHANGELOG.md for what's going on dev branch since last release.

I can do it as well, just tell me when you done with your commits.

**Comment by marelab** [comment]
Have pushed a dev branch with the changes I made so forget about the stable
push and feel free to use the dev push. I had to change a bit the door.esp
because the MQTT sending is controled global, but the side effect is that
you can have only MQTT event logging or local ESP logging. I thought makes
more sense with enabled MQTT logging to disable writing to the flash/eeprom
not sure how many write cycles the ESP will work with intensiv writing.

Am Fr., 14. Juni 2019 um 11:07 Uhr schrieb Ömer Şiar Baysal <
notifications@github.com>:

**Pull request closed without merging**
