### PR TITLE
Fix support for readers other than Wiegand

### LINKED ISSUE #546: Fixing broken mfrc522 and rdm6300 scanners on the latest dev firmware
Today I devoted all my free time to this project in search of problems in which my readers did not work, I fully studied the part of the code responsible for rfid, I was finally able to make everything work, the first problem due to which the readers did not show signs of life at all, as already written in other discussions #506, was the line rfidState = cardSwiped;, which was absent in the processing of the mfrc522, pn532 and rdm6300 readers, after adding this line, the readers started working, but the cards caused the module to reboot, after understanding in detail it turned out that the keys with the Admin label were handled perfectly, and also unfamiliar keys. All keys marked Always, immediately reloaded the module. Going further, I tried to comment out these lines
```
	if (accountType == ACCESS_GRANTED)
	{
		// unsigned long validL = json["validuntil"];
		// unsigned long nowL = now();
		// int hourTz = hour() + config.timeZone;
		// bool officeHour = config.openingHours[weekdayFromMonday(weekday())][hourTz] == '1';
		// if (validL < nowL)
		// {
		// 	processingState = expired;
		// } else if (!officeHour)
		// {
		// 	processingState = notValid;
		// } else
		// {
			processingState = valid;
		// }
	} else if (accountType == ACCESS_ADMIN)
	{
		doEnableWifi = true;
		processingState = validAdmin;
	} else {
		processingState = notValid;
	}
```

And this fixed the whole problem of restarting the module when reading cards.
But also studying the code, I did not see the reverse change of the rfidState parameter, which I think should happen with the line rfidState = waitingCard;.

### PR DESCRIPTION
**Pull request by matjack1**
Fixes #546

### CODE REVIEW

**Comment by Aleks130699** [comment]
Yes, the settings page has all the checkmarks on the time, Okay, I'll try tomorrow with the changes, and with a full reset.

**Comment by Aleks130699** [comment]
this fix did not fix the reboot problem

**Comment by matjack1** [comment]
> this fix did not fix the reboot problem

thank you for the feedback, I'll try with your configuration as soon as possible

**Comment by Aleks130699** [comment]
But downloading a clean configuration helped solve the problem

**Comment by matjack1** [comment]
Thank you for the feedback @Aleks130699 and for the config file to reproduce the error.

I think I've fixed it now, can you please try again and let me know?

Thank you!

**Pull request merged**
