### PR TITLE
add support for RDM6300 125KHz RFID reader

### PR DESCRIPTION
**Pull request by arduino12**
I also wrote a simple library to interface with the RDM6300 RFID reader:
https://github.com/arduino12/rdm6300

### CODE REVIEW

**Comment by arduino12** [comment]
I fixed a bug in the rdm6300 lib (new version is 1.0.1),
Apparently platformio takes 24 hours to pull it...
So I'll re-open the PR  tomorrow...

**Comment by omersiar** [comment]
Actually, you can even set the revision on platformio ini of a git repository.  Platformio Library manager is just a json crawler.  No need to wait. Anyway i will review your PR, thank you.

**Review by omersiar — COMMENTED** [review]
Perfectly clear, amazing, thank you.

**Comment by omersiar** [comment]
Thank you, this is great.

**Comment by arduino12** [comment]
You're welcome,
You have done an amazing job here- great project!

Before I connect two of these to my lab's doors,
I'll add support for the MPR121 Capacitive Touch Keypad:
[https://www.ebay.com/itm/263944297372](https://www.ebay.com/itm/263944297372)
So I can still enter even without the RFID tag, so stay tuned for another PR :)..

PS:
Your ESP8266-RFID-PCB looks great..!

**Comment by omersiar** [comment]
Thanks to @nardev the board is really good, is this keypad works on spi bus? Also there are wiegand readers that also have keypad built in i think that will be more looking good on your lab's door.

**Comment by arduino12** [comment]
This keypad is based on MPR121 - **I2C** interface capacitive touch sensor,
I have worked with those sensors in my previous project and was very impressed by them,
It is better than mechanical keyboards- can work under perspect or glass and feel like "hi-tech" lab..

**Pull request merged**
