### PR TITLE
handle wss on secure connections

### PR DESCRIPTION
**Pull request by thunderace**
With this, you can use a https reverse proxy  to serve your esp8266 contents.

### CODE REVIEW

**Comment by omersiar** [comment]
İ believe this is an opt in change that have no effect without a reverse proxy, right?

**Comment by thunderace** [comment]
You're right. The code only swith to secure websocket if in secure http.

**Comment by thunderace** [comment]
And about the code quality check : i allways use simple quote in javascript code, i will update the PR.

**Comment by thunderace** [comment]
Hum, there is another problem with wss. I close this PR. I'll be back :)

**Pull request closed without merging**
